version: "3.9"

networks:
  traefik_default:
    external: true

volumes:
  reform_discovery:


services:
  reform:
    build:
      dockerfile: Dockerfile-frontend
      args:
        VITE_ALWAYS_ONLINE_PEER_URL: "${VITE_ALWAYS_ONLINE_PEER_URL}"
        VITE_DISCOVERY_SERVER_URL: "${VITE_DISCOVERY_SERVER_URL}"
        VITE_DISCOVERY_SERVER_WEBSOCKET_URL: "${VITE_DISCOVERY_SERVER_WEBSOCKET_URL}"
        VITE_TURN_SERVER: "${VITE_TURN_SERVER}"
    volumes:
      - ./docker/templates:/etc/nginx/templates
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reform.rule=Host(`reform.localhost`)"
      - "traefik.http.routers.reform.entrypoints=web"
    networks:
      - traefik_default
  reform-always-online-peer:
    build:
      dockerfile: Dockerfile-always-online-peer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reform-always-online-peer.rule=Host(`${VITE_ALWAYS_ONLINE_PEER_URL}`)"
      - "traefik.http.routers.reform-always-online-peer.entrypoints=web"
    networks:
      - traefik_default
  reform-discovery:
    build:
      context: https://github.com/reform-org/reform_discovery.git#deployment
    volumes:
      - reform_discovery:/app/data
    environment:
      - JWT_KEY=sdfsdfsdfweffw
      - TURN_SECRET=sdfdsfwefwefwefsgsdgf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reform-discovery.rule=Host(`discovery.localhost`)"
      - "traefik.http.routers.reform-discovery.entrypoints=web"
      - "traefik.http.routers.reform-discovery.service=reform-discovery"
      - "traefik.http.services.reform-discovery.loadbalancer.server.port=3000"
      - "traefik.http.routers.reform-discovery-ws.rule=Host(`ws.discovery.localhost`)"
      - "traefik.http.routers.reform-discovery-ws.entrypoints=web"
      - "traefik.http.routers.reform-discovery-ws.service=reform-discovery-ws"
      - "traefik.http.services.reform-discovery-ws.loadbalancer.server.port=7071"
    networks:
      - traefik_default
  #coturn:
  #  image: coturn/coturn
  #  ports:
  #    - "3478:3478"
  #    - "3478:3478/udp"
  #    - "5349:5349"
  #    - "5349:5349/udp"
  #    - "49152-65535:49152-65535/udp"
