# DOCKER_BUILDKIT=0 docker build -f Dockerfile-frontend .
FROM sbtscala/scala-sbt:eclipse-temurin-jammy-19.0.1_10_1.8.2_3.2.2 AS sbt
WORKDIR /app
COPY . .
RUN sbt fullLinkJS

FROM node AS npm
WORKDIR /app
COPY --from=sbt /app /app
RUN npm ci
RUN npm run build

FROM nginx
WORKDIR /app
RUN cat /etc/nginx/nginx.conf
RUN ls /etc/nginx/conf.d/
RUN cat /etc/nginx/conf.d/*.conf
COPY --from=npm /app/dist /app/dist
