version: "3.3"

services:
  discovery:
    build: discovery
    ports:
      - 3000:3000
      - 7071:7071
    environment:
      - VITE_DISCOVERY_SERVER_PROTOCOL
      - VITE_DISCOVERY_SERVER_HOST
      - VITE_DISCOVERY_SERVER_PATH
      - VITE_DISCOVERY_SERVER_LISTEN_PORT
      - VITE_DISCOVERY_SERVER_PUBLIC_PORT
      - VITE_DISCOVERY_SERVER_WEBSOCKET_PROTOCOL
      - VITE_DISCOVERY_SERVER_WEBSOCKET_HOST
      - VITE_DISCOVERY_SERVER_WEBSOCKET_PATH
      - VITE_DISCOVERY_SERVER_WEBSOCKET_SUBPROTOCOL
      - VITE_DISCOVERY_SERVER_WEBSOCKET_LISTEN_PORT
      - VITE_DISCOVERY_SERVER_WEBSOCKET_PUBLIC_PORT
      - SSO_REDIRECT_URL
      - SSO_CLIENT_ID
      - SSO_CLIENT_SECRET
  peer-dev:
    build:
      context: peer
      dockerfile: Dockerfile-dev
    ports:
      - "5173:5173"
    volumes:
      - './peer/src:/app/peer/src'
  coturn:
    image: docker.io/coturn/coturn
    restart: on-failure
    environment:
      - DETECT_EXTERNAL_IP=yes
      - DETECT_RELAY_IP=yes
      - DETECT_EXTERNAL_IPV6=yes
      - DETECT_RELAY_IPV6=yes
    command: "--verbose --min-port=49160 --max-port=49170 --realm=selfmade4u.de --no-cli --no-tls --no-dtls"
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
      - "49160-49170:49160-49170/udp"
