FROM sbtscala/scala-sbt:eclipse-temurin-jammy-19.0.1_10_1.8.2_3.2.2 AS sbt
WORKDIR /app
COPY . .
RUN sbt webappJVM/package

FROM eclipse-temurin:19.0.1_10-jre AS java
WORKDIR /app
COPY --from=sbt /app/jvm/target/scala-3.2.2/webapp_3-0.1.0-SNAPSHOT.jar /app/webapp_3-0.1.0-SNAPSHOT.jar
CMD ["java", "-jar", "/app/webapp_3-0.1.0-SNAPSHOT.jar"]

