version: "3.9"
services:
  reform:
    build:
      dockerfile: Dockerfile-frontend
    volumes:
      - ./docker/templates:/etc/nginx/templates
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reform.rule=Host(`reform.localhost`)"
      - "traefik.http.routers.reform.entrypoints=web"
  reform-always-online-peer:
    build:
      dockerfile: Dockerfile-always-online-peer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reform-always-online-peer.rule=Host(`reform-always-online-peer.localhost`)"
      - "traefik.http.routers.reform-always-online-peer.entrypoints=web"
  #coturn:
  #  image: coturn/coturn
  #  ports:
  #    - "3478:3478"
  #    - "3478:3478/udp"
  #    - "5349:5349"
  #    - "5349:5349/udp"
  #    - "49152-65535:49152-65535/udp"
