version: "3.9"

services:
  # https://doc.traefik.io/traefik/user-guides/docker-compose/basic-example/#docker-compose-basic-example
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web-$VITE_SERVER_PORT.address=:$VITE_SERVER_PORT"
      - "--entrypoints.web-$VITE_DISCOVERY_SERVER_PORT.address=:$VITE_DISCOVERY_SERVER_PORT"
      - "--entrypoints.web-$VITE_DISCOVERY_SERVER_WEBSOCKET_PORT.address=:$VITE_DISCOVERY_SERVER_WEBSOCKET_PORT"
      - "--entrypoints.web-$VITE_ALWAYS_ONLINE_PEER_PORT.address=:$VITE_ALWAYS_ONLINE_PEER_PORT"
      #- "--entrypoints.tcp-3478.address=:3478"
      #- "--entrypoints.udp-3478.address=:3478/udp"
      #- "--entrypoints.tcp-5349.address=:5349"
      #- "--entrypoints.udp-5349.address=:5349/udp"
    ports:
      - "$VITE_SERVER_PORT:$VITE_SERVER_PORT"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  #whoami:
  #  image: "traefik/whoami"
  #  labels:
  #    - "traefik.enable=true"
  #    - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
  #    - "traefik.http.routers.whoami.entrypoints=web"
