FROM docker.io/sbtscala/scala-sbt:eclipse-temurin-jammy-19.0.1_10_1.8.2_3.2.2 AS sbt
WORKDIR /app
COPY . .
RUN sbt fullLinkJS

FROM docker.io/library/node AS npm
WORKDIR /app
COPY --from=sbt /app /app
RUN npm ci
RUN npm run build -- --mode podman

FROM docker.io/library/nginx
WORKDIR /app
# TODO FIXME we don't need a template, we could directly put the config there
COPY --from=npm /app/dist /app/dist
