FROM docker.io/sbtscala/scala-sbt:eclipse-temurin-jammy-19.0.1_10_1.8.2_3.2.2 AS sbt
ARG VITE_ALWAYS_ONLINE_PEER_LISTEN_PORT
WORKDIR /app
COPY . .
RUN sbt webappJVM/compile
EXPOSE $VITE_ALWAYS_ONLINE_PEER_LISTEN_PORT
CMD ["sbt", "webappJVM/run"]
