version: "3.9"

networks:
  traefik_default:
    external: true

services:
  reform:
    build:
      dockerfile: Dockerfile-frontend
      args:
        VITE_ALWAYS_ONLINE_PEER_URL: "${VITE_ALWAYS_ONLINE_PEER_URL}"
    volumes:
      - ./docker/templates:/etc/nginx/templates
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reform.rule=Host(`reform.localhost`)"
      - "traefik.http.routers.reform.entrypoints=web"
    networks:
      - traefik_default
  reform-always-online-peer:
    build:
      dockerfile: Dockerfile-always-online-peer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reform-always-online-peer.rule=Host(`${VITE_ALWAYS_ONLINE_PEER_URL}`)"
      - "traefik.http.routers.reform-always-online-peer.entrypoints=web"
    networks:
      - traefik_default
  #coturn:
  #  image: coturn/coturn
  #  ports:
  #    - "3478:3478"
  #    - "3478:3478/udp"
  #    - "5349:5349"
  #    - "5349:5349/udp"
  #    - "49152-65535:49152-65535/udp"
