FROM node AS npm
ARG VITE_DISCOVERY_SERVER_PATH
ARG VITE_DISCOVERY_SERVER_LISTEN_PORT
ARG VITE_DISCOVERY_SERVER_WEBSOCKET_PATH
ARG VITE_DISCOVERY_SERVER_WEBSOCKET_SUBPROTOCOL
ARG VITE_DISCOVERY_SERVER_WEBSOCKET_LISTEN_PORT
WORKDIR /app
COPY . .
RUN npm ci
EXPOSE $VITE_DISCOVERY_SERVER_LISTEN_PORT $VITE_DISCOVERY_SERVER_WEBSOCKET_LISTEN_PORT
CMD ["npx", "ts-node", "index.ts"]