name: Scala JVM Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - run: npm ci
    - name: Test
      run: sbt clean coverage webappJVM/test webappJVM/coverageReport
    - uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: jvm/target/scala-*/scoverage-report/
