name: Scala Selenium

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        map: [
          { os: ubuntu-latest, browser: firefox },
          { os: ubuntu-latest, browser: chrome },
          { os: macos-latest,  browser: safari }
        ]

    runs-on: ${{ matrix.map.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - run: npm ci
    - name: Build ScalaJS
      run: sbt fastLinkJS
    - name: Build JavaScript
      run: npm run build
    - name: Preview
      run: npm run preview &
    - name: Workflow tests
      run: SELENIUM_BROWSER=${{ matrix.map.browser }} npm run test
    - name: Selenium
      if: ${{ matrix.map.browser == 'safari' }}
      run: SELENIUM_BROWSER=${{ matrix.map.browser }} npm run selenium
