name: Scala Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "sbt"
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "npm"
      - run: npm ci
      - name: Build ScalaJS
        run: sbt fastLinkJS
      - name: Build JavaScript
        run: npm run build -- --mode lukasschreiber
