name: Scala Selenium

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        map: [
          { os: ubuntu-latest, browser: firefox },
          { os: ubuntu-latest, browser: chrome }
        ]

    runs-on: ${{ matrix.map.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'sbt'
    - uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
    - name: Cache scalablytyped
      id: cache-scalablytyped
      uses: actions/cache@v3
      with:
        path: ~/.cache/scalablytyped
        key: ${{ runner.os }}-scalablytyped
    - run: npm ci
    - name: Build ScalaJS
      run: sbt fastLinkJS
    - name: Build JavaScript
      run: npm run build
    - name: Preview
      run: npm run preview &
    - name: Workflow tests
      run: SELENIUM_BROWSER=${{ matrix.map.browser }} npm run test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: screenshot
        path: screenshot.png
    - name: Selenium
      run: SELENIUM_BROWSER=${{ matrix.map.browser }} npm run selenium
