name: Scala Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
    - name: Cache scalablytyped
      id: cache-scalablytyped
      uses: actions/cache@v3
      with:
        path: ~/.cache/scalablytyped
        key: ${{ runner.os }}-scalablytyped
    - run: npm ci
    - name: Build ScalaJS
      run: sbt fastLinkJS
    - name: Build JavaScript
      run: npm run build
