name: Selenium

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      browser:
        required: true
        type: string

permissions:
  contents: read

jobs:
  selenium:
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "sbt"
      - name: Run Coturn
        uses: addnab/docker-run-action@v3
        with:
          image: coturn/coturn
          options: --network host
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      - name: Build ScalaJS
        run: sbt fastLinkJS
      - name: Build JavaScript
        run: VITE_SELENIUM=true npm run build -- --mode lukasschreiber
      - name: Preview
        run: npm run preview &
      - name: Workflow tests
        run: SELENIUM_BROWSER=${{ inputs.browser }} npm run test
      - name: Selenium
        run: SELENIUM_BROWSER=${{ inputs.browser }} npm run selenium
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: screenshots
